void main( 
	   float4      diffuseST        : TEXCOORD0,

	   uniform sampler2D   diffuseImage  : TEXUNIT4,
           out float4  color0 : COLOR0,
           out float4  color1 : COLOR1,
           out float4  color2 : COLOR2)
{
    float2 texcoord = diffuseST.xy;

    float4 diffuse = tex2D(diffuseImage, texcoord).rgba;
 
    color0.xyzw = float4(0, 0, 0, 0);
    color1.xyzw = float4(0, 0, 0, 0);
    color2.xyzw = diffuse;
}

